plugins {
	id 'org.springframework.boot'
}

springBoot {
    mainClass = 'com.app.JavaHexagonalStructureApplication'
}


dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'

    // Modules Dependencies
    implementation project(':java-hexagonal-structure-application')
    implementation project(':java-hexagonal-structure-domain')
    implementation project(':java-hexagonal-structure-infrastructure')
}

jar { enabled = false }